// <auto-generated />
using System;
using CreditService.Estructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditService.Migrations
{
    [DbContext(typeof(CreditDbContext))]
    [Migration("20260921034629_FrecuenciaSeguroIngreso")]
    partial class FrecuenciaSeguroIngreso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditService.Dominio.Simulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CuotaFija")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("FechaSimulacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FrecuenciaPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IncluyeSeguroDesgravamen")
                        .HasColumnType("boolean");

                    b.Property<decimal>("IngresoMinimoRequerido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PlazoMeses")
                        .HasColumnType("integer");

                    b.Property<decimal>("TasaAnualAplicada")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("TipoCreditoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalInteresAleman")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalInteresFrances")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TipoCreditoId");

                    b.HasIndex("UsuarioId", "FechaSimulacion");

                    b.ToTable("simulaciones", (string)null);
                });

            modelBuilder.Entity("CreditService.Dominio.TipoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TasaAnual")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("TasaSeguroDesgravamenMensual")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("tipos_credito", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "CONSUMO",
                            Descripcion = "Adquisición de bienes de consumo o pago de servicios.",
                            Nombre = "Crédito de Consumo",
                            TasaAnual = 15.50m,
                            TasaSeguroDesgravamenMensual = 0.0500m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "INMOBILIARIO",
                            Descripcion = "Compra, construcción o remodelación de vivienda.",
                            Nombre = "Crédito Inmobiliario",
                            TasaAnual = 8.50m,
                            TasaSeguroDesgravamenMensual = 0.0400m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "MICROCREDITO",
                            Descripcion = "Financiamiento para actividades productivas a pequeña escala.",
                            Nombre = "Microcrédito",
                            TasaAnual = 22.00m,
                            TasaSeguroDesgravamenMensual = 0.0700m
                        });
                });

            modelBuilder.Entity("CreditService.Dominio.Simulacion", b =>
                {
                    b.HasOne("CreditService.Dominio.TipoCredito", "TipoCredito")
                        .WithMany()
                        .HasForeignKey("TipoCreditoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoCredito");
                });
#pragma warning restore 612, 618
        }
    }
}
