// <auto-generated />
using System;
using CreditService.Estructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditService.Migrations
{
    [DbContext(typeof(CreditDbContext))]
    partial class CreditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CreditService.Dominio.Simulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CuotaFija")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaSimulacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrecuenciaPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IncluyeSeguroDesgravamen")
                        .HasColumnType("bit");

                    b.Property<decimal>("IngresoMinimoRequerido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlazoMeses")
                        .HasColumnType("int");

                    b.Property<decimal>("TasaAnualAplicada")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TipoCreditoId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalInteresAleman")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalInteresFrances")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TipoCreditoId");

                    b.HasIndex("UsuarioId", "FechaSimulacion");

                    b.ToTable("simulaciones", (string)null);
                });

            modelBuilder.Entity("CreditService.Dominio.TipoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TasaAnual")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TasaSeguroDesgravamenMensual")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("tipos_credito", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Categoria = "Consumo",
                            Codigo = "CONSUMO",
                            Descripcion = "Adquisición de bienes de consumo o pago de servicios.",
                            Nombre = "Crédito de Consumo",
                            TasaAnual = 15.50m,
                            TasaSeguroDesgravamenMensual = 0.0500m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Categoria = "Vivienda",
                            Codigo = "INMOBILIARIO",
                            Descripcion = "Compra, construcción o remodelación de vivienda.",
                            Nombre = "Crédito Inmobiliario",
                            TasaAnual = 8.50m,
                            TasaSeguroDesgravamenMensual = 0.0400m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Categoria = "Microcrédito",
                            Codigo = "MICROCREDITO",
                            Descripcion = "Financiamiento para actividades productivas a pequeña escala.",
                            Nombre = "Microcrédito",
                            TasaAnual = 22.00m,
                            TasaSeguroDesgravamenMensual = 0.0700m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Categoria = "Productivo",
                            Codigo = "PRODUCTIVO_CORPORATIVO",
                            Descripcion = "Empresas con ventas anuales superiores a cinco millones de dólares.",
                            Nombre = "Productivo Corporativo",
                            TasaAnual = 6.79m,
                            TasaSeguroDesgravamenMensual = 0.0300m
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Categoria = "Productivo",
                            Codigo = "PRODUCTIVO_EMPRESARIAL",
                            Descripcion = "Empresas con ventas anuales entre uno y cinco millones de dólares.",
                            Nombre = "Productivo Empresarial",
                            TasaAnual = 8.62m,
                            TasaSeguroDesgravamenMensual = 0.0350m
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Categoria = "Productivo",
                            Codigo = "PRODUCTIVO_PYMES",
                            Descripcion = "Pequeñas y medianas empresas con ventas anuales de hasta un millón de dólares.",
                            Nombre = "Productivo PYMES",
                            TasaAnual = 9.18m,
                            TasaSeguroDesgravamenMensual = 0.0450m
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Categoria = "Educativo",
                            Codigo = "EDUCATIVO",
                            Descripcion = "Financiamiento de estudios de grado, posgrado y formación profesional.",
                            Nombre = "Crédito Educativo",
                            TasaAnual = 8.95m,
                            TasaSeguroDesgravamenMensual = 0.0450m
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Categoria = "Educativo",
                            Codigo = "EDUCATIVO_SOCIAL",
                            Descripcion = "Estudios para personas en situación de vulnerabilidad, con tasa preferente.",
                            Nombre = "Crédito Educativo Social",
                            TasaAnual = 5.49m,
                            TasaSeguroDesgravamenMensual = 0.0400m
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Categoria = "Vivienda",
                            Codigo = "VIVIENDA_INTERES_SOCIAL",
                            Descripcion = "Primera vivienda para familias de bajos ingresos, con tope de precio regulado.",
                            Nombre = "Vivienda de Interés Social",
                            TasaAnual = 4.99m,
                            TasaSeguroDesgravamenMensual = 0.0400m
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Categoria = "Vivienda",
                            Codigo = "VIVIENDA_INTERES_PUBLICO",
                            Descripcion = "Primera vivienda dentro de proyectos calificados por el Estado.",
                            Nombre = "Vivienda de Interés Público",
                            TasaAnual = 4.99m,
                            TasaSeguroDesgravamenMensual = 0.0400m
                        });
                });

            modelBuilder.Entity("CreditService.Dominio.Simulacion", b =>
                {
                    b.HasOne("CreditService.Dominio.TipoCredito", "TipoCredito")
                        .WithMany()
                        .HasForeignKey("TipoCreditoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoCredito");
                });
#pragma warning restore 612, 618
        }
    }
}
