<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AssetService.Dominio</RootNamespace>
  </PropertyGroup>

  <!-- El centro de la cebolla no referencia ningun otro proyecto ni paquete. -->

</Project>
