-- =============================================================================
--  Sistema de Simulación de Créditos — esquema completo de base de datos
--  Universidad Técnica de Ambato
-- =============================================================================
--
--  Cada microservicio es dueño de su propia base (patrón Database per Service):
--    · authdb   -> AuthService   : identidades de los usuarios
--    · creditdb -> CreditService : catálogo de productos e historial de simulaciones
--    · assetdb  -> AssetService  : garantías declaradas y sus categorías
--
--  Ejecución:
--      psql -U postgres -h localhost -f database/database.sql
--
--  Este archivo NO es la fuente de la verdad: se genera a partir de las
--  migraciones de EF Core, que sí lo son. Para regenerarlo tras un cambio
--  de modelo, en cada servicio:
--      dotnet ef migrations script --idempotent -o <servicio>.sql
--  y volver a unirlos bajo estas cabeceras, quitando la marca BOM que EF Core
--  escribe al inicio de cada archivo: incrustada a mitad del script, psql la
--  leería como parte de una sentencia y fallaría.
--
--  Los scripts son idempotentes: se pueden ejecutar varias veces sin duplicar
--  objetos ni datos.
--
--  Nota: en desarrollo no hace falta ejecutar nada de esto. Al arrancar, cada
--  servicio crea su base y aplica sus migraciones automáticamente. Este archivo
--  existe para despliegues donde la aplicación no tiene permiso de DDL, y como
--  documentación legible del esquema.
-- =============================================================================


-- =============================================================================
--  1. Creación de las bases
-- =============================================================================
-- PostgreSQL no admite "CREATE DATABASE IF NOT EXISTS"; si ya existen, estas
-- sentencias fallarán y psql continuará con el resto del archivo.

CREATE DATABASE authdb;
CREATE DATABASE creditdb;
CREATE DATABASE assetdb;


-- =============================================================================
--  2. authdb — AuthService
-- =============================================================================

\connect authdb

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916054155_CreacionInicial') THEN
    CREATE TABLE usuarios (
        "Id" uuid NOT NULL,
        "NombreCompleto" character varying(150) NOT NULL,
        "Email" character varying(150) NOT NULL,
        "PasswordHash" character varying(255) NOT NULL,
        "FechaRegistro" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_usuarios" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916054155_CreacionInicial') THEN
    CREATE UNIQUE INDEX "IX_usuarios_Email" ON usuarios ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260916054155_CreacionInicial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260916054155_CreacionInicial', '10.0.12');
    END IF;
END $EF$;
COMMIT;



-- =============================================================================
--  3. creditdb — CreditService
-- =============================================================================

\connect creditdb

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918234236_CreacionInicial') THEN
    CREATE TABLE tipos_credito (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Codigo" character varying(30) NOT NULL,
        "Nombre" character varying(100) NOT NULL,
        "TasaAnual" numeric(5,2) NOT NULL,
        "Descripcion" character varying(300) NOT NULL,
        "Activo" boolean NOT NULL,
        CONSTRAINT "PK_tipos_credito" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918234236_CreacionInicial') THEN
    CREATE TABLE simulaciones (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "TipoCreditoId" integer NOT NULL,
        "Monto" numeric(18,2) NOT NULL,
        "PlazoMeses" integer NOT NULL,
        "TasaAnualAplicada" numeric(5,2) NOT NULL,
        "CuotaFija" numeric(18,2) NOT NULL,
        "TotalInteresFrances" numeric(18,2) NOT NULL,
        "TotalInteresAleman" numeric(18,2) NOT NULL,
        "FechaSimulacion" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_simulaciones" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_simulaciones_tipos_credito_TipoCreditoId" FOREIGN KEY ("TipoCreditoId") REFERENCES tipos_credito ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918234236_CreacionInicial') THEN
    INSERT INTO tipos_credito ("Id", "Activo", "Codigo", "Descripcion", "Nombre", "TasaAnual")
    VALUES (1, TRUE, 'CONSUMO', 'Adquisición de bienes de consumo o pago de servicios.', 'Crédito de Consumo', 15.5);
    INSERT INTO tipos_credito ("Id", "Activo", "Codigo", "Descripcion", "Nombre", "TasaAnual")
    VALUES (2, TRUE, 'INMOBILIARIO', 'Compra, construcción o remodelación de vivienda.', 'Crédito Inmobiliario', 8.5);
    INSERT INTO tipos_credito ("Id", "Activo", "Codigo", "Descripcion", "Nombre", "TasaAnual")
    VALUES (3, TRUE, 'MICROCREDITO', 'Financiamiento para actividades productivas a pequeña escala.', 'Microcrédito', 22.0);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918234236_CreacionInicial') THEN
    CREATE INDEX "IX_simulaciones_TipoCreditoId" ON simulaciones ("TipoCreditoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918234236_CreacionInicial') THEN
    CREATE INDEX "IX_simulaciones_UsuarioId_FechaSimulacion" ON simulaciones ("UsuarioId", "FechaSimulacion");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918234236_CreacionInicial') THEN
    CREATE UNIQUE INDEX "IX_tipos_credito_Codigo" ON tipos_credito ("Codigo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918234236_CreacionInicial') THEN
    PERFORM setval(
        pg_get_serial_sequence('tipos_credito', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM tipos_credito) + 1,
            nextval(pg_get_serial_sequence('tipos_credito', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260918234236_CreacionInicial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260918234236_CreacionInicial', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921034629_FrecuenciaSeguroIngreso') THEN
    ALTER TABLE tipos_credito ADD "TasaSeguroDesgravamenMensual" numeric(7,4) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921034629_FrecuenciaSeguroIngreso') THEN
    ALTER TABLE simulaciones ADD "FrecuenciaPago" character varying(20) NOT NULL DEFAULT 'Mensual';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921034629_FrecuenciaSeguroIngreso') THEN
    ALTER TABLE simulaciones ADD "IncluyeSeguroDesgravamen" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921034629_FrecuenciaSeguroIngreso') THEN
    ALTER TABLE simulaciones ADD "IngresoMinimoRequerido" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921034629_FrecuenciaSeguroIngreso') THEN
    UPDATE simulaciones SET "IngresoMinimoRequerido" = CEIL("CuotaFija" / 0.40 * 100) / 100 WHERE "IngresoMinimoRequerido" = 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921034629_FrecuenciaSeguroIngreso') THEN
    UPDATE tipos_credito SET "TasaSeguroDesgravamenMensual" = 0.05
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921034629_FrecuenciaSeguroIngreso') THEN
    UPDATE tipos_credito SET "TasaSeguroDesgravamenMensual" = 0.04
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921034629_FrecuenciaSeguroIngreso') THEN
    UPDATE tipos_credito SET "TasaSeguroDesgravamenMensual" = 0.07
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921034629_FrecuenciaSeguroIngreso') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260921034629_FrecuenciaSeguroIngreso', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923001233_CatalogoAmpliadoSegmentosBCE') THEN
    ALTER TABLE tipos_credito ADD "Categoria" character varying(40) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923001233_CatalogoAmpliadoSegmentosBCE') THEN
    UPDATE tipos_credito SET "Categoria" = 'Consumo'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923001233_CatalogoAmpliadoSegmentosBCE') THEN
    UPDATE tipos_credito SET "Categoria" = 'Vivienda'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923001233_CatalogoAmpliadoSegmentosBCE') THEN
    UPDATE tipos_credito SET "Categoria" = 'Microcrédito'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923001233_CatalogoAmpliadoSegmentosBCE') THEN
    INSERT INTO tipos_credito ("Id", "Activo", "Categoria", "Codigo", "Descripcion", "Nombre", "TasaAnual", "TasaSeguroDesgravamenMensual")
    VALUES (4, TRUE, 'Productivo', 'PRODUCTIVO_CORPORATIVO', 'Empresas con ventas anuales superiores a cinco millones de dólares.', 'Productivo Corporativo', 6.79, 0.03);
    INSERT INTO tipos_credito ("Id", "Activo", "Categoria", "Codigo", "Descripcion", "Nombre", "TasaAnual", "TasaSeguroDesgravamenMensual")
    VALUES (5, TRUE, 'Productivo', 'PRODUCTIVO_EMPRESARIAL', 'Empresas con ventas anuales entre uno y cinco millones de dólares.', 'Productivo Empresarial', 8.62, 0.035);
    INSERT INTO tipos_credito ("Id", "Activo", "Categoria", "Codigo", "Descripcion", "Nombre", "TasaAnual", "TasaSeguroDesgravamenMensual")
    VALUES (6, TRUE, 'Productivo', 'PRODUCTIVO_PYMES', 'Pequeñas y medianas empresas con ventas anuales de hasta un millón de dólares.', 'Productivo PYMES', 9.18, 0.045);
    INSERT INTO tipos_credito ("Id", "Activo", "Categoria", "Codigo", "Descripcion", "Nombre", "TasaAnual", "TasaSeguroDesgravamenMensual")
    VALUES (7, TRUE, 'Educativo', 'EDUCATIVO', 'Financiamiento de estudios de grado, posgrado y formación profesional.', 'Crédito Educativo', 8.95, 0.045);
    INSERT INTO tipos_credito ("Id", "Activo", "Categoria", "Codigo", "Descripcion", "Nombre", "TasaAnual", "TasaSeguroDesgravamenMensual")
    VALUES (8, TRUE, 'Educativo', 'EDUCATIVO_SOCIAL', 'Estudios para personas en situación de vulnerabilidad, con tasa preferente.', 'Crédito Educativo Social', 5.49, 0.04);
    INSERT INTO tipos_credito ("Id", "Activo", "Categoria", "Codigo", "Descripcion", "Nombre", "TasaAnual", "TasaSeguroDesgravamenMensual")
    VALUES (9, TRUE, 'Vivienda', 'VIVIENDA_INTERES_SOCIAL', 'Primera vivienda para familias de bajos ingresos, con tope de precio regulado.', 'Vivienda de Interés Social', 4.99, 0.04);
    INSERT INTO tipos_credito ("Id", "Activo", "Categoria", "Codigo", "Descripcion", "Nombre", "TasaAnual", "TasaSeguroDesgravamenMensual")
    VALUES (10, TRUE, 'Vivienda', 'VIVIENDA_INTERES_PUBLICO', 'Primera vivienda dentro de proyectos calificados por el Estado.', 'Vivienda de Interés Público', 4.99, 0.04);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923001233_CatalogoAmpliadoSegmentosBCE') THEN
    PERFORM setval(
        pg_get_serial_sequence('tipos_credito', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM tipos_credito) + 1,
            nextval(pg_get_serial_sequence('tipos_credito', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923001233_CatalogoAmpliadoSegmentosBCE') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260923001233_CatalogoAmpliadoSegmentosBCE', '10.0.12');
    END IF;
END $EF$;
COMMIT;



-- =============================================================================
--  4. assetdb — AssetService
-- =============================================================================

\connect assetdb

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923205851_CreacionInicial') THEN
    CREATE TABLE categorias_activo (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Codigo" character varying(30) NOT NULL,
        "Nombre" character varying(100) NOT NULL,
        "Descripcion" character varying(300) NOT NULL,
        "Habilitada" boolean NOT NULL,
        CONSTRAINT "PK_categorias_activo" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923205851_CreacionInicial') THEN
    CREATE TABLE activos (
        "Id" uuid NOT NULL,
        "UsuarioId" uuid NOT NULL,
        "CategoriaId" integer NOT NULL,
        "Nombre" character varying(150) NOT NULL,
        "Descripcion" character varying(300) NOT NULL,
        "ValorEstimado" numeric(18,2) NOT NULL,
        "FechaAdquisicion" date NOT NULL,
        "FechaRegistro" timestamp with time zone NOT NULL,
        "FechaActualizacion" timestamp with time zone,
        CONSTRAINT "PK_activos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_activos_categorias_activo_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES categorias_activo ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923205851_CreacionInicial') THEN
    INSERT INTO categorias_activo ("Id", "Codigo", "Descripcion", "Habilitada", "Nombre")
    VALUES (1, 'VEHICULO', 'Automóviles, motocicletas y vehículos de carga.', TRUE, 'Vehículo');
    INSERT INTO categorias_activo ("Id", "Codigo", "Descripcion", "Habilitada", "Nombre")
    VALUES (2, 'INMUEBLE', 'Casas, departamentos, terrenos y locales comerciales.', TRUE, 'Inmueble');
    INSERT INTO categorias_activo ("Id", "Codigo", "Descripcion", "Habilitada", "Nombre")
    VALUES (3, 'MAQUINARIA', 'Equipos productivos, herramientas y maquinaria industrial.', TRUE, 'Maquinaria y equipo');
    INSERT INTO categorias_activo ("Id", "Codigo", "Descripcion", "Habilitada", "Nombre")
    VALUES (4, 'INVERSION', 'Depósitos a plazo, acciones y participaciones.', TRUE, 'Inversión financiera');
    INSERT INTO categorias_activo ("Id", "Codigo", "Descripcion", "Habilitada", "Nombre")
    VALUES (5, 'OTRO', 'Bienes que no encajan en las categorías anteriores.', TRUE, 'Otros bienes');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923205851_CreacionInicial') THEN
    CREATE INDEX "IX_activos_CategoriaId" ON activos ("CategoriaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923205851_CreacionInicial') THEN
    CREATE INDEX "IX_activos_UsuarioId_FechaRegistro" ON activos ("UsuarioId", "FechaRegistro");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923205851_CreacionInicial') THEN
    CREATE UNIQUE INDEX "IX_categorias_activo_Codigo" ON categorias_activo ("Codigo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923205851_CreacionInicial') THEN
    PERFORM setval(
        pg_get_serial_sequence('categorias_activo', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM categorias_activo) + 1,
            nextval(pg_get_serial_sequence('categorias_activo', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260923205851_CreacionInicial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260923205851_CreacionInicial', '10.0.12');
    END IF;
END $EF$;
COMMIT;

