// <auto-generated />
using System;
using AssetService.Estructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssetService.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    [Migration("20260923205851_CreacionInicial")]
    partial class CreacionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssetService.Dominio.Activo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaAdquisicion")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId", "FechaRegistro");

                    b.ToTable("activos", (string)null);
                });

            modelBuilder.Entity("AssetService.Dominio.CategoriaActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("Habilitada")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("categorias_activo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "VEHICULO",
                            Descripcion = "Automóviles, motocicletas y vehículos de carga.",
                            Habilitada = true,
                            Nombre = "Vehículo"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "INMUEBLE",
                            Descripcion = "Casas, departamentos, terrenos y locales comerciales.",
                            Habilitada = true,
                            Nombre = "Inmueble"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "MAQUINARIA",
                            Descripcion = "Equipos productivos, herramientas y maquinaria industrial.",
                            Habilitada = true,
                            Nombre = "Maquinaria y equipo"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "INVERSION",
                            Descripcion = "Depósitos a plazo, acciones y participaciones.",
                            Habilitada = true,
                            Nombre = "Inversión financiera"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "OTRO",
                            Descripcion = "Bienes que no encajan en las categorías anteriores.",
                            Habilitada = true,
                            Nombre = "Otros bienes"
                        });
                });

            modelBuilder.Entity("AssetService.Dominio.Activo", b =>
                {
                    b.HasOne("AssetService.Dominio.CategoriaActivo", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
